# Exportar Información

Exportar información es parte importante del proceso de análisis de datos. En esta sección veremos algunas herramientas que permiten conectar los resultados del análisis hecho en Stata con los reportes que queremos crear en Word. 

### Stata Markdown

* Herramienta para crear informes que sean reproducibles y en donde los datos, códigos y operaciones están conectadas.  
* Básicamente una intersección entre texto narrativo y
* Es posible generar informes en distintos formatos (ej. html, docx, pdf). Hoy veremos como generar un informe en Word y una presentación en HTML. 
* Stata Markdown es especialmente útil para: 
  + **Informes rutinarios:** Informe semanas/mensual sobre un conjunto de datos que se actualizan constantemente. 
  + **Documentar análisis:** Es posible integrar reportes intermedios en un trabajo de análisis de datos. Estos informes pueden ser de utilidad para detectar errores y para supervisión en equipos de trabajo. 
        
Stata Markdown y otras herramientas similares son claves para mejorar en términos de \alert{reproducibilidad}. Algunos argumentos basados en \cite{rodriguez2017literate}:

* **Ayuda a documentación:** En la fase de procesamiento de datos podemos describir todos los pasos utilizados para convertir los datos brutos en variables de análisis, produciendo un documento con un buen formato, más claro y legible. Es posible pensar en estos informes como productos intermedios.
* En la fase de análisis de los datos, podemos incluir el código, explicar las razones para probar determinados modelos, incluir los resultados, las tablas y las figuras, y comentar los resultados, todo ello sin tener que cortar y pegar de forma tediosa y propensa a errores.
* En la fase de presentación, podemos elaborar un informe centrado en los resultados, con la opción de ocultar los comandos reales utilizados para que no aparezcan en el documento final.

Algunos conceptos

* **Markdown:** Es un lenguaje que permite escribir documentos en texto plano. Los archivos escritos en Markdown tienen la extensión `md`. 
* **Stata Markdown:** Es la variación especifica para Stata. Se implementa a través del comando `markstat` hecho por [Germán Rodriguez](https://data.princeton.edu/stata/markdown). Estos archivos tiene extensión `.stmd`.

#### Instalación

En Stata, ejecuta estos comandos: 

* `ssc install` markstat
* `ssc install` whereis  
* Instalar padcoc desde `pandoc.org/installing`
* Decirle a `markstat` donde encontrar pandoc. En mi caso es: 
```{stata}
whereis pandoc "C:\Users\nicol\AppData\Local\Pandoc\pandoc.exe"
```

#### Funcionalidades

Algunos elementos que vamos a utilizar en Stata Markdown: 

* Ecuaciones y notación matemática utilizando \LaTeX (para los que lo sepan utilizar). 
* Hacer títulos y encabezados. 
* Enfatizar texto (negritas e itálicas). 
* Armas listas numeradas y no numeradas. 
* Poder mostrar líneas de código, resultados directamente de Stata. Esto incluye Mata. 
* Insertar quiebres de páginas: `\newpage`. 

#### Generar un documento

Como mencionamos anteriormente es posible generar un documento de word, pdf o html que contenga todos los códigos, resultados, tablas y figuras hechas en Stata. Para generar un documento es necesario: 
        
* Escribir en tu editor de códigos preferido un archivo en formato `stmd`. En nuestro caso escribiremos un archivo que se llama `ejemplo1.stmd`. Guardar el archivo en tu carpeta de trabajo. 
* Ejecutar el comando `markstat` según el tipo de archivo que desee generar. En nuestro caso será:
```{stata}
markstat using ejemplo1, strict docx
```

### Putdocx

La ventaja de `putdocx` radica en que es posible personalizar un poco más las tablas. Esto permite conectar el informe final con el trabajo de análisis de datos. 

#### Algunos comandos útiles

Crear, pegar y guardar documentos:

* `putdocx begin`: Crea un archivo docx para exportar.
* `putdocx describe`: Describe los contenidos de archivo. 
* `putdocx save`: Guarda y cierra el archivo. 
* `putdocx clear`: Cierra el archivo sin guardar. 
* `putdocx append`: Combina el contenido de múltiples archivos. 

Insertar quiebres de páginas:
* `putdocx pagebreak`: Agrega una nueva página.
* `putdocx sectionbreak`: Agrega una nueva sección. 

Agregar párrafos con texto e imágenes:
* `putdocx paragraph`: Agrega un nuevo párrafo. 
* `putdocx text`: Agrega un bloque de texto a un párrafo. 
* `putdocx image`: Agrega una imagen al párrafo.

#### Tablas:

`putdocx table`: Crea una nueva tabla en el documento la que puede contener resultados de estimaciones, estadística descriptiva o datos. 
`putdocx sectionbreak`: Agrega una nueva sección. 
