---
title: "Análisis de Datos con Stata, R y Python"
author: "Nicolás Campos Bijit"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    highlight: tango
bibliography: references.bib
biblio-style: apalike
link-citations: yes
description: Libro enfocado en enseñar análisis de datos utilizando Stata, R y Python
---
# Introducción 

Estas notas están diseñadas para aquellos que buscan aprender herramientas de análisis de datos en R, Python y Stata. Están estructuradas como notas de clase, lo que implica una progresión secuencial a través de las sesiones. Las notas de Python y R forman parte de un curso básico, mientras que el curso de Stata corresponde a un nivel avanzado. Para la sección de Stata, estas notas enfatizan buenas prácticas de programación, diseño de programas (archivos ado), matrices en Stata (mata), técnicas avanzadas de replicación y manejo de grandes bases de datos.

Con el tiempo, estas notas de clase han evolucionado y seguirán haciéndolo. Se han enriquecido gracias a las contribuciones de varias personas. Agradezco especialmente a Camila Vivanco, Diego Menares, Catalina Buzio, Felix Ordoñez por sus contribuciones. Sin su colaboración, estas notas no serían lo que son hoy. También expreso mi gratitud a Benjamín Pinto, quien me ayudó a adaptar las notas a este formato.

Además, estas notas están basadas en varios materiales de acceso público. A lo largo de ellas, se indican las referencias bibliográficas correspondientes y se proporcionan recursos gratuitos para aquellos que deseen ampliar o consolidar sus conocimientos. En muchos casos, los ejemplos han sido tomados de este material adicional. Siempre hago un esfuerzo por citar adecuadamente las fuentes, con la intención de respetar la autoría original y proporcionar acceso a recursos valiosos para los lectores de estas notas. ¡Déjenme saber si encuentran errores!

Para sugerencias, preguntas o recomendaciones, no duden en escribirme a ncamposbijit@gmail.com.

